package io.github.alexandrupascu.maze.bench;

import io.github.alexandrupascu.maze.bench.LearningCurves.Curve;
import io.github.alexandrupascu.maze.bench.LearningCurves.FamilyResult;
import io.github.alexandrupascu.maze.bench.LearningCurves.Result;
import io.github.alexandrupascu.maze.bench.LearningCurves.Settings;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.TreeSet;

/** Writes the learning curves as CSV and Markdown, with the same formatting rules as the benchmark. */
public final class LearningReport {
  private LearningReport() {}

  public static void write(Result result, Path directory) throws IOException {
    Files.createDirectories(directory);
    Files.writeString(directory.resolve("learning.csv"), curvesCsv(result), StandardCharsets.UTF_8);
    Files.writeString(directory.resolve("learning-summary.csv"), summaryCsv(result), StandardCharsets.UTF_8);
    Files.writeString(directory.resolve("learning.md"), markdown(result), StandardCharsets.UTF_8);
  }

  public static String curvesCsv(Result result) {
    int cells = result.settings().cells();
    StringBuilder out = new StringBuilder("layout,loops,cells,robot,run,mean_steps,shortest_mean_steps\n");
    for (FamilyResult family : result.families()) {
      for (Curve curve : family.curves()) {
        for (int run = 0; run < curve.meanSteps().size(); run++) {
          out.append(format("%s,%.2f,%d,%s,%d,%.2f,%.2f%n", family.family().layout().id(), family.family().loops(),
              cells, curve.learner().id(), run + 1, curve.meanSteps().get(run), family.shortest()));
        }
      }
    }
    return out.toString();
  }

  public static String summaryCsv(Result result) {
    Settings settings = result.settings();
    StringBuilder out = new StringBuilder(
        "layout,loops,cells,robot,mazes,runs,converged_share,shortest_from_run_mean,total_steps_mean\n");
    for (FamilyResult family : result.families()) {
      for (Curve curve : family.curves()) {
        out.append(format("%s,%.2f,%d,%s,%d,%d,%.4f,%s,%.1f%n", family.family().layout().id(), family.family().loops(),
            settings.cells(), curve.learner().id(), settings.mazes(), settings.runs(),
            (double) curve.converged() / settings.mazes(),
            curve.converged() == 0 ? "" : format("%.2f", curve.shortestFromRun()), curve.totalSteps()));
      }
    }
    return out.toString();
  }

  public static String markdown(Result result) {
    Settings settings = result.settings();
    List<Integer> shown = shownRuns(settings.runs());
    StringBuilder out = new StringBuilder("# Learning curves\n\n");
    out.append(format(
        "Generated by `./gradlew run --args=\"learn%s\"`: %d mazes of %dx%d cells for each maze type (seed %d, the "
            + "benchmark's first %d mazes of that size). Every robot runs each maze %d times and keeps what it learned "
            + "between runs. Steps are means over the mazes.%n%n",
        arguments(settings), settings.mazes(), settings.cells(), settings.cells(), settings.seed(), settings.mazes(),
        settings.runs()));
    out.append(format("\"Shortest from run\" is the run from which every remaining run was a shortest route, "
        + "averaged over the mazes where that happened within %d runs. \"Converged\" is the share of those mazes. "
        + "\"Total\" is the mean number of steps over all %d runs.%n", settings.runs(), settings.runs()));
    for (FamilyResult family : result.families()) {
      out.append(format("%n## %s (shortest route %.1f steps)%n%n", family.family().label(settings.cells()),
          family.shortest()));
      out.append("| Robot |");
      for (int run : shown) {
        out.append(" Run ").append(run).append(" |");
      }
      out.append(" Shortest from run | Converged | Total |\n|---|");
      out.append("---:|".repeat(shown.size() + 3)).append('\n');
      for (Curve curve : family.curves()) {
        out.append("| ").append(curve.learner().title().replace("*", "\\*")).append(" |");
        for (int run : shown) {
          out.append(format(" %.1f |", curve.meanSteps().get(run - 1)));
        }
        out.append(curve.converged() == 0 ? " — |" : format(" %.1f |", curve.shortestFromRun()));
        out.append(format(" %.0f%% | %.0f |%n", 100.0 * curve.converged() / settings.mazes(), curve.totalSteps()));
      }
    }
    return out.toString();
  }

  // The first few runs, then every tenth, and the last.
  static List<Integer> shownRuns(int runs) {
    TreeSet<Integer> shown = new TreeSet<>(List.of(1, 2, 3, 5));
    for (int run = 10; run < runs; run += 10) {
      shown.add(run);
    }
    shown.add(runs);
    return new ArrayList<>(shown.headSet(runs, true));
  }

  private static String arguments(Settings settings) {
    Settings defaults = Settings.defaults();
    StringBuilder text = new StringBuilder();
    if (settings.mazes() != defaults.mazes()) {
      text.append(" --mazes ").append(settings.mazes());
    }
    if (settings.runs() != defaults.runs()) {
      text.append(" --runs ").append(settings.runs());
    }
    if (settings.cells() != defaults.cells()) {
      text.append(" --cells ").append(settings.cells());
    }
    if (settings.seed() != defaults.seed()) {
      text.append(" --seed ").append(settings.seed());
    }
    return text.toString();
  }

  private static String format(String pattern, Object... values) {
    return String.format(Locale.ROOT, pattern, values).replace("\r\n", "\n");
  }
}
