package io.github.alexandrupascu.maze.bench;

import io.github.alexandrupascu.maze.agents.Agent;
import io.github.alexandrupascu.maze.bench.Benchmark.AgentSummary;
import io.github.alexandrupascu.maze.bench.Benchmark.Config;
import io.github.alexandrupascu.maze.bench.Benchmark.Report;
import io.github.alexandrupascu.maze.bench.Benchmark.SearchSummary;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;

/** Writes benchmark reports with locale-independent number formatting and LF line endings. */
public final class ReportWriter {
  private ReportWriter() {}

  public static void write(Report report, Path directory) throws IOException {
    Files.createDirectories(directory);
    Files.writeString(directory.resolve("summary.csv"), agentsCsv(report), StandardCharsets.UTF_8);
    Files.writeString(directory.resolve("search.csv"), searchCsv(report), StandardCharsets.UTF_8);
    Files.writeString(directory.resolve("summary.md"), markdown(report), StandardCharsets.UTF_8);
  }

  public static String agentsCsv(Report report) {
    StringBuilder out = new StringBuilder(
        "layout,loops,cells,agent,mazes,run1_mean_steps,run2_mean_steps,shortest_mean_steps,"
            + "run1_over_run2_median,run2_over_shortest_mean,run2_shortest_share,collisions,failures\n");
    for (AgentSummary row : report.agents()) {
      Config config = row.config();
      out.append(format("%s,%.2f,%d,%s,%d,%.2f,%.2f,%.2f,%.3f,%.3f,%.4f,%d,%d%n",
          config.layout().id(), config.loops(), config.cells(), row.agent().id(), row.mazes(),
          row.run1Steps(), row.run2Steps(), row.shortestSteps(), row.medianSpeedup(),
          row.run2OverShortest(), (double) row.run2Shortest() / row.mazes(), row.collisions(),
          row.failures()));
    }
    return out.toString();
  }

  public static String searchCsv(Report report) {
    StringBuilder out = new StringBuilder(
        "layout,loops,cells,mazes,open_tiles_mean,dijkstra_expanded_mean,astar_expanded_mean\n");
    for (SearchSummary row : report.searches()) {
      Config config = row.config();
      out.append(format("%s,%.2f,%d,%d,%.2f,%.2f,%.2f%n", config.layout().id(), config.loops(),
          config.cells(), row.mazes(), row.openTiles(), row.dijkstraExpanded(), row.aStarExpanded()));
    }
    return out.toString();
  }

  public static String markdown(Report report) {
    Benchmark.Settings settings = report.settings();
    StringBuilder out = new StringBuilder("# Benchmark results\n\n");
    out.append(format(
        "Generated by `./gradlew run --args=\"benchmark%s\"`: %d seeded mazes per configuration "
            + "(seed %d), two runs per robot on each maze. Sizes are in cells; a 15x15-cell maze is "
            + "31x31 tiles. The start is the top-left cell and the target the bottom-right cell. "
            + "Loops are the share of internal walls knocked through after carving a perfect maze.%n%n",
        arguments(settings), settings.mazes(), settings.seed()));
    out.append(outcomes(report)).append("\n\n");

    out.append("## Mean steps per run\n\n");
    out.append("| Maze | Shortest route | Coursework run 1 | Coursework run 2 | Map planner run 1 | Map planner run 2 |\n");
    out.append("|---|---:|---:|---:|---:|---:|\n");
    for (Config config : Benchmark.configs(settings)) {
      AgentSummary coursework = find(report, config, Agent.COURSEWORK);
      AgentSummary planner = find(report, config, Agent.MAP_PLANNER);
      out.append(format("| %s | %.1f | %.1f | %.1f | %.1f | %.1f |%n", config.label(),
          coursework.shortestSteps(), coursework.run1Steps(), coursework.run2Steps(),
          planner.run1Steps(), planner.run2Steps()));
    }

    out.append("\n## What the second run gained\n\n");
    out.append("Speed-up is the median of run 1 ÷ run 2 per maze. \"Shortest\" is the share of mazes where run 2 matched the A* route.\n\n");
    out.append("| Maze | Coursework speed-up | Coursework run 2 ÷ shortest | Coursework shortest | Map planner speed-up | Map planner run 2 ÷ shortest | Map planner shortest |\n");
    out.append("|---|---:|---:|---:|---:|---:|---:|\n");
    for (Config config : Benchmark.configs(settings)) {
      AgentSummary coursework = find(report, config, Agent.COURSEWORK);
      AgentSummary planner = find(report, config, Agent.MAP_PLANNER);
      out.append(format("| %s | %.2f× | %.2f× | %.0f%% | %.2f× | %.2f× | %.0f%% |%n", config.label(),
          coursework.medianSpeedup(), coursework.run2OverShortest(), share(coursework),
          planner.medianSpeedup(), planner.run2OverShortest(), share(planner)));
    }

    out.append("\n## A* against Dijkstra on the full map\n\n");
    out.append("Both find a shortest route; the Manhattan-distance heuristic lets A* expand fewer tiles.\n\n");
    out.append("| Maze | Open tiles | Dijkstra expanded | A* expanded | A* saving |\n");
    out.append("|---|---:|---:|---:|---:|\n");
    for (SearchSummary row : report.searches()) {
      out.append(format("| %s | %.1f | %.1f | %.1f | %.0f%% |%n", row.config().label(), row.openTiles(),
          row.dijkstraExpanded(), row.aStarExpanded(), 100 * (1 - row.aStarExpanded() / row.dijkstraExpanded())));
    }
    return out.toString();
  }

  private static String outcomes(Report report) {
    StringBuilder text = new StringBuilder();
    for (Agent agent : Agent.values()) {
      long failures = 0;
      long collisions = 0;
      for (AgentSummary row : report.agents()) {
        if (row.agent() == agent) {
          failures += row.failures();
          collisions += row.collisions();
        }
      }
      text.append(text.isEmpty() ? "" : " ").append(format("%s: %d unfinished runs, %d wall collisions.",
          agent.title(), failures, collisions));
    }
    return text.toString();
  }

  private static String arguments(Benchmark.Settings settings) {
    Benchmark.Settings defaults = Benchmark.Settings.defaults();
    StringBuilder text = new StringBuilder();
    if (settings.mazes() != defaults.mazes()) {
      text.append(" --mazes ").append(settings.mazes());
    }
    if (settings.seed() != defaults.seed()) {
      text.append(" --seed ").append(settings.seed());
    }
    if (!settings.sizes().equals(defaults.sizes())) {
      text.append(" --sizes ").append(String.join(",", settings.sizes().stream().map(String::valueOf).toList()));
    }
    return text.toString();
  }

  private static double share(AgentSummary row) {
    return 100.0 * row.run2Shortest() / row.mazes();
  }

  private static AgentSummary find(Report report, Config config, Agent agent) {
    for (AgentSummary row : report.agents()) {
      if (row.config().equals(config) && row.agent() == agent) {
        return row;
      }
    }
    throw new IllegalArgumentException("no result for " + agent.id() + " on " + config.label());
  }

  private static String format(String pattern, Object... values) {
    return String.format(Locale.ROOT, pattern, values).replace("\r\n", "\n");
  }
}
