package io.github.alexandrupascu.maze.bench;

import io.github.alexandrupascu.maze.agents.Agent;
import io.github.alexandrupascu.maze.bench.Benchmark.AgentSummary;
import io.github.alexandrupascu.maze.bench.Benchmark.Config;
import io.github.alexandrupascu.maze.bench.Benchmark.Report;
import io.github.alexandrupascu.maze.bench.Benchmark.SearchSummary;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;

/** Writes benchmark reports with locale-independent number formatting and LF line endings. */
public final class ReportWriter {
  /** The robots that explore, in the order the tables show them; the A* oracle is the yardstick. */
  private static final List<Agent> EXPLORERS = List.of(Agent.COURSEWORK, Agent.MAP_PLANNER, Agent.ROUTE_PROVER);

  private ReportWriter() {}

  public static void write(Report report, Path directory) throws IOException {
    Files.createDirectories(directory);
    Files.writeString(directory.resolve("summary.csv"), agentsCsv(report), StandardCharsets.UTF_8);
    Files.writeString(directory.resolve("search.csv"), searchCsv(report), StandardCharsets.UTF_8);
    Files.writeString(directory.resolve("summary.md"), markdown(report), StandardCharsets.UTF_8);
  }

  public static String agentsCsv(Report report) {
    StringBuilder out = new StringBuilder(
        "layout,loops,cells,agent,mazes,run1_mean_steps,run2_mean_steps,shortest_mean_steps,"
            + "run1_over_run2_median,run2_over_shortest_mean,run2_shortest_share,run1_search_expansions_mean,"
            + "collisions,failures\n");
    for (AgentSummary row : report.agents()) {
      Config config = row.config();
      out.append(format("%s,%.2f,%d,%s,%d,%.2f,%.2f,%.2f,%.3f,%.3f,%.4f,%.1f,%d,%d%n",
          config.layout().id(), config.loops(), config.cells(), row.agent().id(), row.mazes(),
          row.run1Steps(), row.run2Steps(), row.shortestSteps(), row.medianSpeedup(),
          row.run2OverShortest(), (double) row.run2Shortest() / row.mazes(), row.run1Expansions(),
          row.collisions(), row.failures()));
    }
    return out.toString();
  }

  public static String searchCsv(Report report) {
    StringBuilder out = new StringBuilder(
        "layout,loops,cells,mazes,open_tiles_mean,dijkstra_expanded_mean,astar_expanded_mean,"
            + "map_planner_scratch_run1_steps_mean,map_planner_scratch_run1_expanded_mean,"
            + "map_planner_dstar_run1_steps_mean,map_planner_dstar_run1_expanded_mean,map_planner_same_moves\n");
    for (SearchSummary row : report.searches()) {
      Config config = row.config();
      out.append(format("%s,%.2f,%d,%d,%.2f,%.2f,%.2f,%.2f,%.1f,%.2f,%.1f,%d%n", config.layout().id(), config.loops(),
          config.cells(), row.mazes(), row.openTiles(), row.dijkstraExpanded(), row.aStarExpanded(),
          row.scratchSteps(), row.scratchExpanded(), row.incrementalSteps(), row.incrementalExpanded(), row.sameMoves()));
    }
    return out.toString();
  }

  public static String markdown(Report report) {
    Benchmark.Settings settings = report.settings();
    List<Config> configs = Benchmark.configs(settings);
    StringBuilder out = new StringBuilder("# Benchmark results\n\n");
    out.append(format(
        "Generated by `./gradlew run --args=\"benchmark%s\"`: %d seeded mazes per configuration "
            + "(seed %d), two runs per robot on each maze. Sizes are in cells; a 15x15-cell maze is "
            + "31x31 tiles. The start is the top-left cell and the target the bottom-right cell. "
            + "Loops: after carving a perfect maze, that share of the walls left between cells is knocked through.%n%n",
        arguments(settings), settings.mazes(), settings.seed()));
    out.append(outcomes(report)).append("\n\n");

    out.append("## Mean steps per run\n\n");
    out.append("| Maze | Shortest route | Coursework run 1 | Coursework run 2 | Map planner run 1 | Map planner run 2 "
        + "| Route prover run 1 | Route prover run 2 |\n");
    out.append("|---|---:|---:|---:|---:|---:|---:|---:|\n");
    for (Config config : configs) {
      out.append("| ").append(config.label()).append(format(" | %.1f", find(report, config, Agent.COURSEWORK).shortestSteps()));
      for (Agent agent : EXPLORERS) {
        AgentSummary row = find(report, config, agent);
        out.append(format(" | %.1f | %.1f", row.run1Steps(), row.run2Steps()));
      }
      out.append(" |\n");
    }

    out.append("\n## The second run against the shortest route\n\n");
    out.append("Run 2 ÷ shortest is the mean over mazes. \"Shortest\" is the share of mazes where run 2 was as short as the A\\* route.\n\n");
    out.append("| Maze | Coursework run 2 ÷ shortest | Coursework shortest | Map planner run 2 ÷ shortest | Map planner shortest "
        + "| Route prover run 2 ÷ shortest | Route prover shortest |\n");
    out.append("|---|---:|---:|---:|---:|---:|---:|\n");
    for (Config config : configs) {
      out.append("| ").append(config.label());
      for (Agent agent : EXPLORERS) {
        AgentSummary row = find(report, config, agent);
        out.append(format(" | %.2f× | %.0f%%", row.run2OverShortest(), 100.0 * row.run2Shortest() / row.mazes()));
      }
      out.append(" |\n");
    }

    out.append("\n## When proving pays off\n\n");
    out.append("The route prover may explore more than the map planner on run 1 to prove its route, then saves steps on "
        + "every later run. The last column is the number of runs of the same maze after which it has walked fewer or "
        + "equal steps in total, from the mean steps above.\n\n");
    out.append("| Maze | Run 1: prover − planner | Each later run: planner − prover | Prover ahead in total from run |\n");
    out.append("|---|---:|---:|---:|\n");
    for (Config config : configs) {
      AgentSummary planner = find(report, config, Agent.MAP_PLANNER);
      AgentSummary prover = find(report, config, Agent.ROUTE_PROVER);
      double extra = prover.run1Steps() - planner.run1Steps();
      double saved = planner.run2Steps() - prover.run2Steps();
      String breakEven = extra <= 0 ? "1" : saved <= 0 ? "never" : String.valueOf(1 + (long) Math.ceil(extra / saved));
      out.append(format("| %s | %+.1f | %+.1f | %s |%n", config.label(), extra, saved, breakEven));
    }

    out.append("\n## Learning across mazes\n\n");
    out.append("First runs of the frontier explorer, which walks to the frontier cell with the lowest score, with the "
        + "map planner's freespace rule and with weights trained by the cross-entropy method on other mazes "
        + "([training.md](training.md)). Every maze here is unseen by the training; it used only 15x15 mazes. "
        + "\"Change in mean steps\" compares the mean steps; \"mean per-maze change\" averages each maze's own "
        + "ratio, which is what training minimised, so one long run cannot hide many small losses.\n\n");
    out.append("| Maze | Map planner | Freespace rule | Learned | Change in mean steps | Mean per-maze change "
        + "| Mazes better / worse |\n");
    out.append("|---|---:|---:|---:|---:|---:|---:|\n");
    for (Benchmark.ExplorationSummary row : report.explorations()) {
      Config config = row.config();
      AgentSummary freespace = find(report, config, Agent.FRONTIER_EXPLORER);
      AgentSummary learned = find(report, config, Agent.LEARNED_EXPLORER);
      out.append(format("| %s | %.1f | %.1f | %.1f | %+.1f%% | %+.1f%% | %d / %d |%n", config.label(),
          find(report, config, Agent.MAP_PLANNER).run1Steps(), freespace.run1Steps(), learned.run1Steps(),
          100 * (learned.run1Steps() / freespace.run1Steps() - 1), 100 * (row.meanRatio() - 1), row.better(),
          row.worse()));
    }

    out.append("\n## Speed-up from run 1 to run 2\n\n");
    out.append("The median over mazes of run 1 ÷ run 2.\n\n");
    out.append("| Maze | Coursework | Map planner | Route prover |\n");
    out.append("|---|---:|---:|---:|\n");
    for (Config config : configs) {
      out.append("| ").append(config.label());
      for (Agent agent : EXPLORERS) {
        out.append(format(" | %.2f×", find(report, config, agent).medianSpeedup()));
      }
      out.append(" |\n");
    }

    out.append("\n## Search work\n\n");
    out.append("### A\\* against Dijkstra on the full map\n\n");
    out.append("Both find a shortest route; the Manhattan-distance heuristic lets A\\* expand fewer tiles.\n\n");
    out.append("| Maze | Open tiles | Dijkstra expanded | A\\* expanded | A\\* saving |\n");
    out.append("|---|---:|---:|---:|---:|\n");
    for (SearchSummary row : report.searches()) {
      out.append(format("| %s | %.1f | %.1f | %.1f | %.0f%% |%n", row.config().label(), row.openTiles(),
          row.dijkstraExpanded(), row.aStarExpanded(), 100 * (1 - row.aStarExpanded() / row.dijkstraExpanded())));
    }
    out.append("\n### The map planner's first run: D\\* Lite against searching again from scratch\n\n");
    out.append("The same robot with two search engines. Searching from scratch runs a new breadth-first search whenever a "
        + "wall blocks the route; D\\* Lite repairs only what each newly seen wall changes. \"Same moves\" counts the "
        + "mazes where both took exactly the same path.\n\n");
    out.append("| Maze | Same moves | Steps from scratch | Steps with D\\* Lite | Tiles expanded from scratch "
        + "| Tiles expanded by D\\* Lite | Less work |\n");
    out.append("|---|---:|---:|---:|---:|---:|---:|\n");
    for (SearchSummary row : report.searches()) {
      out.append(format("| %s | %d/%d | %.1f | %.1f | %.0f | %.0f | %.1f× |%n", row.config().label(), row.sameMoves(),
          row.mazes(), row.scratchSteps(), row.incrementalSteps(), row.scratchExpanded(), row.incrementalExpanded(),
          row.scratchExpanded() / row.incrementalExpanded()));
    }
    return out.toString();
  }

  private static String outcomes(Report report) {
    StringBuilder text = new StringBuilder();
    for (Agent agent : Benchmark.AGENTS) {
      long failures = 0;
      long collisions = 0;
      for (AgentSummary row : report.agents()) {
        if (row.agent() == agent) {
          failures += row.failures();
          collisions += row.collisions();
        }
      }
      text.append(text.isEmpty() ? "" : " ").append(format("%s: %d unfinished runs, %d wall collisions.",
          agent.title(), failures, collisions));
    }
    return text.toString();
  }

  private static String arguments(Benchmark.Settings settings) {
    Benchmark.Settings defaults = Benchmark.Settings.defaults();
    StringBuilder text = new StringBuilder();
    if (settings.mazes() != defaults.mazes()) {
      text.append(" --mazes ").append(settings.mazes());
    }
    if (settings.seed() != defaults.seed()) {
      text.append(" --seed ").append(settings.seed());
    }
    if (!settings.sizes().equals(defaults.sizes())) {
      text.append(" --sizes ").append(String.join(",", settings.sizes().stream().map(String::valueOf).toList()));
    }
    return text.toString();
  }

  private static AgentSummary find(Report report, Config config, Agent agent) {
    for (AgentSummary row : report.agents()) {
      if (row.config().equals(config) && row.agent() == agent) {
        return row;
      }
    }
    throw new IllegalArgumentException("no result for " + agent.id() + " on " + config.label());
  }

  private static String format(String pattern, Object... values) {
    return String.format(Locale.ROOT, pattern, values).replace("\r\n", "\n");
  }
}
