package io.github.alexandrupascu.maze.bench;

import io.github.alexandrupascu.maze.learning.CrossEntropyMethod;
import io.github.alexandrupascu.maze.learning.CrossEntropyMethod.Generation;
import io.github.alexandrupascu.maze.learning.CrossEntropyMethod.Settings;
import io.github.alexandrupascu.maze.learning.ExplorationPolicy;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;

/** Writes the exploration policy's training history as CSV and Markdown, and the trained weights. */
public final class TrainingReport {
  private TrainingReport() {}

  public static void write(CrossEntropyMethod.Result result, Path reports, Path model) throws IOException {
    Files.createDirectories(reports);
    Files.writeString(reports.resolve("training.csv"), csv(result), StandardCharsets.UTF_8);
    Files.writeString(reports.resolve("training.md"), markdown(result), StandardCharsets.UTF_8);
    if (model.getParent() != null) {
      Files.createDirectories(model.getParent());
    }
    Files.writeString(model, "# Trained by ./gradlew run --args=\"train" + arguments(result.settings())
        + "\"; see reports/training.md\n" + result.policy().format(), StandardCharsets.UTF_8);
  }

  static String csv(CrossEntropyMethod.Result result) {
    StringBuilder out = new StringBuilder("generation,best_cost,mean_cost");
    for (String feature : ExplorationPolicy.FEATURES) {
      out.append(",mean_").append(feature.replace('-', '_'));
    }
    out.append('\n');
    for (Generation generation : result.history()) {
      out.append(format("%d,%.5f,%.5f", generation.number(), generation.bestCost(), generation.meanCost()));
      for (double weight : generation.meanWeights()) {
        out.append(format(",%.6f", weight));
      }
      out.append('\n');
    }
    return out.toString();
  }

  static String markdown(CrossEntropyMethod.Result result) {
    Settings settings = result.settings();
    StringBuilder out = new StringBuilder("# Training the exploration policy\n\n");
    out.append(format("Generated by `./gradlew run --args=\"train%s\"`. The cross-entropy method ran for %d generations "
            + "of %d sampled policies, refitting its Gaussian to the best %d each time. Every policy explored the same "
            + "%d training mazes: %d of each of the six maze types, %dx%d cells, from seed %d, which the benchmark "
            + "never uses.%n%n",
        arguments(settings), settings.generations(), settings.population(), settings.elites(),
        6 * settings.mazesPerType(), settings.mazesPerType(), settings.cells(), settings.cells(), settings.seed()));
    out.append("A policy's cost is the mean over the training mazes of its first-run steps divided by the freespace "
        + "rule's on the same maze, so the freespace rule costs exactly 1 and every maze counts equally. Results on the "
        + "benchmark's own mazes, which training never saw, are in [summary.md](summary.md#learning-across-mazes); its "
        + "\"mean per-maze change\" is the same measure.\n\n");
    out.append(format("The trained policy costs **%.4f** on the training mazes.%n%n", result.cost()));
    out.append("| Feature | Weight |\n|---|---:|\n");
    double[] weights = result.policy().weights();
    for (int i = 0; i < weights.length; i++) {
      out.append(format("| %s | %.3f |%n", ExplorationPolicy.FEATURES.get(i), weights[i]));
    }
    out.append("\n| Generation | Cheapest policy | Mean of all policies |\n|---:|---:|---:|\n");
    for (Generation generation : result.history()) {
      out.append(format("| %d | %.4f | %.4f |%n", generation.number(), generation.bestCost(), generation.meanCost()));
    }
    return out.toString();
  }

  private static String arguments(Settings settings) {
    Settings defaults = Settings.defaults();
    StringBuilder text = new StringBuilder();
    if (settings.generations() != defaults.generations()) {
      text.append(" --generations ").append(settings.generations());
    }
    if (settings.population() != defaults.population()) {
      text.append(" --population ").append(settings.population());
    }
    if (settings.elites() != defaults.elites()) {
      text.append(" --elites ").append(settings.elites());
    }
    if (settings.mazesPerType() != defaults.mazesPerType()) {
      text.append(" --mazes ").append(settings.mazesPerType());
    }
    if (settings.cells() != defaults.cells()) {
      text.append(" --cells ").append(settings.cells());
    }
    if (settings.seed() != defaults.seed()) {
      text.append(" --seed ").append(settings.seed());
    }
    return text.toString();
  }

  private static String format(String pattern, Object... values) {
    return String.format(Locale.ROOT, pattern, values).replace("\r\n", "\n");
  }
}
